#!/usr/bin/make
## makefile (for essence-p001)
## Mac Radigan

.PHONY: build clean run install
.DEFAULT_GOAL := build

default: build

build:
	stack $@

install:
	stack $@

clean:
	stack $@

run:
	~/.local/bin/essence-p001-exe

## *EOF*
