#!/usr/bin/make
## makefile (for wadler-1992)
## Mac Radigan

.PHONY: build clean run install
.DEFAULT_GOAL := build

default: build

target = essence-p001

build:
	$(MAKE) -C $(target) $@

install:
	$(MAKE) -C $(target) $@

clean:
	$(MAKE) -C $(target) $@

run:
	$(MAKE) -C $(target) $@

## *EOF*
